version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

# Forzamos la instalación de las extensiones que queremos explotar
python:
  install:
    - requirements: requirements.txt
